### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by lukewarmcustard** [mdwalters/lemonade#12]
app launches fine but when clicking on login nothing happens, running fedoa 39

Lemonade version: 2023.10.29
libadwaita version: 1.4.0
GTK version: 4.12.3

flatpak run ml.mdwalters.Lemonade
[Errno 17] File exists: '/run/user/1000/app/ml.mdwalters.Lemonade/cache'
Downloading icon for Sashatown Central News Agency
Successfully downloaded icon for Sashatown Central News Agency
No icon found for ameliatoami, skipping
Downloading icon for 2meirl4meirl
Error getting icon for 2meirl4meirl
Downloading icon for Protogen
Error getting icon for Protogen
No icon found for Like this? You may like..., skipping
No icon found for yesyesyesno, skipping
No icon found for Pamvegan, skipping
Downloading icon for Technology(ru)
Successfully downloaded icon for Technology(ru)
Downloading icon for Visiting France
Successfully downloaded icon for Visiting France
Downloading icon for sdpadresfans
Successfully downloaded icon for sdpadresfans

**Comment by theycallhermax** [comment]
that is intentional, and besides, lemonade is going to be undergoing a rewrite today
