### ISSUE TITLE
(bug)Login button not working

### ISSUE THREAD

**Issue by Drummyralf** [mdwalters/lemonade#13]
Hiya,

I installed Lemonade through flatpak. The application opens up fine, but if I try to click the "login" in the hamburger menu, nothing happens.

If I click on any of the generic threads that it shows, nothing happens. It does register that click though, as seen in my console log below. It always registers the same community clicked though, even if I click different ones.. A click on "Login" is not registered at all.

The About and Quit App in the menu work just fine.
  
  Lemonade version: 2023.10.29
  libadwaita version: 1.4.4
  GTK version: 4.12.5

I'm using Linux Mint 21.3 Cinnamon, version 6.0.4.
Linux Kernel 6.5.0-28 Generic

My Terminal log if I run flatpak run ml.mdwalters.Lemonade:

      flatpak run ml.mdwalters.Lemonade
      [Errno 17] File exists: '/run/user/1000/app/ml.mdwalters.Lemonade/cache'
      Downloading icon for Steamed Hams
      Error getting icon for Steamed Hams
      Downloading icon for Dog Diet
      Error getting icon for Dog Diet
      No icon found for Retro Status, skipping
      No icon found for Africa, skipping
      Downloading icon for Samba (software)
      Successfully downloaded icon for Samba (software)
      No icon found for VoxeLibre, skipping
      Downloading icon for East Asia
      Error getting icon for East Asia
      Downloading icon for Warframe
      Successfully downloaded icon for Warframe
      Downloading icon for musika
      Successfully downloaded icon for musika
      Downloading icon for Playing Cards
      Successfully downloaded icon for Playing Cards
      Community 212665 clicked
      Community 212665 clicked
      Community 212665 clicked
      Community 212665 clicked
      Community 212665 clicked

**Comment by theycallhermax** [comment]
lemonade is currently undergoing a rewrite and it will be fixed there
see https://github.com/theycallhermax/lemonade/issues/12#issuecomment-1841079270
