### ISSUE TITLE
Quit application with Ctrl + Q

### ISSUE THREAD

**Issue by Mars7x** [mdwalters/lemonade#4]
Every Gnome app has this shortcut, so it would be nice for consistency.

**Comment by maymage** [comment]
Quitting the app means no notifications though. Better

* `Ctrl+W` to close the window, leaving the app running in the background
* `Ctrl+Shift+Q` or so for really closing. 

See https://gitlab.gnome.org/Teams/Design/whiteboards/-/issues/164
