### ISSUE TITLE
Doesn't open

### ISSUE THREAD

**Issue by berserkwarwolf** [mdwalters/lemonade#5]
[warmaster@fmv-p2 ~]$ flatpak -v run ml.mdwalters.Lemonade
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/warmaster/.local/share/flatpak
F: Opening user flatpak installation at path /home/warmaster/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/warmaster/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/44/4078027bba432a34c29220e86e005b05db89371141bee6f58774932a7b27d119/files/lib32 does not exist
F: Cleaning up unused container id 509571444
F: Allocated instance id 982296864
F: Add defaults in dir /ml/mdwalters/Lemonade/
F: Add locks in dir /ml/mdwalters/Lemonade/
F: Allowing dri access
F: Allowing wayland access
F: Running 'bwrap --args 39 xdg-dbus-proxy --args=41'
F: Running 'bwrap --args 39 lemonade'
[warmaster@fmv-p2 ~]$ 

Any ideas ?

**Comment by theycallhermax** [comment]
what version is lemonade on?

**Comment by berserkwarwolf** [comment]
> what version is lemonade on?

After being unable to make it launch, I uninstalled and reinstalled the flatpak, so I can only assume it was the latest available version on flathub.

**Comment by phil-lipp** [comment]
Same here. Just installed a couple of minutes ago from flathub.
I'm using Debian 12 with Gnome and a couple of Gnome extensions, if that is relevant.

```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/phillipp/.local/share/flatpak
F: Opening user flatpak installation at path /home/phillipp/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/phillipp/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/44/4078027bba432a34c29220e86e005b05db89371141bee6f58774932a7b27d119/files/lib32 does not exist
F: Cleaning up unused container id 375778171
F: Allocated instance id 667027144
F: Add defaults in dir /ml/mdwalters/Lemonade/
F: Add locks in dir /ml/mdwalters/Lemonade/
F: Allowing dri access
F: Allowing wayland access
F: Running 'bwrap --args 40 xdg-dbus-proxy --args=42'
F: Running 'bwrap --args 40 lemonade'
```

**Comment by amadeusp** [comment]
Just installed version 2023.07.01 via Flathub/Flatpak on my 6.3.5-2-MANJARO GNOME 44.1 and get:
```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/amadeus/.local/share/flatpak
F: Opening user flatpak installation at path /home/amadeus/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/ml.mdwalters.Lemonade/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/amadeus/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/44/4078027bba432a34c29220e86e005b05db89371141bee6f58774932a7b27d119/files/lib32 does not exist
F: Cleaning up unused container id 1427832495
F: Allocated instance id 3853138960
F: Add defaults in dir /ml/mdwalters/Lemonade/
F: Add locks in dir /ml/mdwalters/Lemonade/
F: Allowing dri access
F: Allowing wayland access
F: Running 'bwrap --args 37 xdg-dbus-proxy --args=40'
F: Running 'bwrap --args 37 lemonade'
```
