### ISSUE TITLE
Icon change

### ISSUE THREAD

**Issue by daudix** [mdwalters/lemonade#8]
Hi, I have been working on a new icon for Lemonade that has a bit more interesting look, opening this for further discussion

![image](https://github.com/mdwalters/lemonade/assets/77155297/0934bae1-b796-4082-8198-faba287d4181)

![image](https://github.com/mdwalters/lemonade/assets/77155297/87db574c-973a-4cde-b646-5087231d1d83)

**Comment by theycallhermax** [comment]
hey, thanks! i like the second one; could you make the lemon on the can a bit more yellow?

**Comment by daudix** [comment]
I can, tho it will blend with the yellow "wave". although I can try using something in the middle between yellow and orange

**Comment by daudix** [comment]
![изображение](https://github.com/mdwalters/lemonade/assets/77155297/a44053c2-84cf-409f-9318-1f7ba77fe6c8)

**Comment by daudix** [comment]
One more variant

![image](https://github.com/mdwalters/lemonade/assets/77155297/7d7f4dac-1b03-46e6-983d-47c54cddf3d3)

**Comment by theycallhermax** [comment]
> One more variant
> 
> ![image](https://user-images.githubusercontent.com/77155297/266678966-7d7f4dac-1b03-46e6-983d-47c54cddf3d3.png)

perfect! could you share the svg of the prod/nightly icon so i can include it in the repo?

**Comment by daudix** [comment]
Gonna create PR in a second ;)
